apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-app-front
  template:
    metadata:
      labels:
        app: weather-app-front
    spec:
      containers:
      - name: weather-app-front
        image: gonpaz/weather-front:1.1
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_BACK_URL
          value: ""
